export const PORTFOLIO_AI_LIMITS = {
  assistantMessageCharacters: 8_000,
  historyMessageCharacters: 1_200,
  historyMessages: 8,
  linkLabelCharacters: 200,
  projectNameCharacters: 120,
  projectSummaryCharacters: 2_000,
  projectTechnologies: 20,
  providerMaxRetries: 0,
  providerOutputCharacters: 8_000,
  providerOutputTokens: 700,
  providerTimeoutMs: 8_000,
  questionCharacters: 1_200,
  rateLimitMaxTrackedClients: 5_000,
  rateLimitRequests: 24,
  rateLimitWindowMs: 60_000,
  requestBodyBytes: 24_576,
  technologyCharacters: 80,
} as const;
