export const resumeFile = {
  name: "Nikki_Neil_Carino_CV.pdf",
  url: "/resume/Nikki_Neil_Carino_CV.pdf",
  mimeType: "application/pdf",
} as const;

export const portfolioProfile = {
  identity: {
    fullName: "Nikki Neil P. Cariño",
    shortName: "Nikki",
    degree: "Bachelor of Science in Information Technology",
    university: "University of Santo Tomas",
    studyPeriod: "2022-2026",
    graduationYear: 2026,
    careerLevel: "Entry-level / recent graduate",
    location: "Quezon City, Philippines",
  },
  summary:
    "A recent BS Information Technology graduate with hands-on experience in software development, software quality assurance, prompt engineering, AI-assisted workflows, backend development, API integration, mobile application development, databases, Git workflows, and Agile collaboration.",
  strongestAreas: [
    "Full-stack web development",
    "Software quality assurance",
    "Backend development and API integration",
    "AI-assisted development and prompt engineering",
    "Mobile application development",
  ],
  contact: {
    email: "nikkineil.carino@gmail.com",
    phoneDisplay: "0949-343-3164",
    phoneHref: "+639493433164",
    github: "https://github.com/nikkineilcarino",
    portfolio: "https://carino-portfolio.vercel.app",
  },
  resume: resumeFile,
  skills: {
    programmingLanguages: [
      "Python",
      "PHP",
      "TypeScript",
      "JavaScript",
      "Kotlin",
      "Dart",
      "HTML5",
      "CSS3",
    ],
    frameworksAndLibraries: [
      "React",
      "Next.js",
      "Laravel",
      "Flutter",
      "Django",
      "Django REST Framework",
      "Tailwind CSS",
      "Material UI",
      "Recharts",
    ],
    databasesAndBackend: [
      "MySQL",
      "PostgreSQL",
      "Firebase",
      "SQLite",
      "REST APIs",
      "API integration",
    ],
    testingAndQa: [
      "Manual testing",
      "Functional testing",
      "Regression testing",
      "Test-case design",
      "Test-case execution",
      "Bug reporting",
      "Defect documentation",
      "Defect verification",
      "Browser automation exposure with Playwright",
      "API testing exposure",
    ],
    aiAndMachineLearningTools: [
      "Prompt engineering",
      "OpenAI Codex",
      "Claude",
      "Google Colab",
      "Roboflow",
      "Teachable Machine",
      "YOLOv8",
      "TensorFlow Lite",
    ],
    developerAndDesignTools: [
      "Git",
      "GitHub",
      "Visual Studio Code",
      "Android Studio",
      "Figma",
      "Canva",
    ],
  },
  internship: {
    company: "Microgenesis Business Systems",
    roles: [
      "QA Intern",
      "Software Developer Intern",
      "Prompt-engineering exposure",
    ],
    year: 2026,
    projects: ["Microgenesis Central Hub", "OneOPS", "BTr HCM"],
    responsibilities: [
      "Performed manual, functional, and regression testing.",
      "Created and executed test cases.",
      "Reported and documented defects.",
      "Verified fixes and issue resolutions.",
      "Supported development using Python and TypeScript.",
      "Designed prompts for development, documentation, and QA workflows.",
      "Participated in Agile sprint planning and issue tracking.",
      "Collaborated with developers, QA personnel, and project stakeholders.",
    ],
  },
  education: [
    {
      institution: "University of Santo Tomas",
      program: "Bachelor of Science in Information Technology",
      period: "2022-2026",
    },
  ],
  projects: [
    {
      name: "RecycLens",
      type: "Academic capstone project",
      summary:
        "A gamified Android application designed to teach kindergarten students proper waste disposal using image recognition.",
      role: "Project Manager and Mobile Developer",
      technologies: [
        "Kotlin",
        "Python",
        "YOLOv8",
        "TensorFlow Lite",
        "Google Colab",
        "SQLite",
        "Roboflow",
      ],
      features: [
        "Classifies waste as biodegradable or non-biodegradable.",
        "Supports camera capture and gallery upload.",
        "Includes Trash Sorting and Street Cleanup games.",
        "Supports three difficulty levels, English and Filipino, text-to-speech, and local storage.",
        "Designed for teacher-guided use by children aged four to six.",
      ],
      metrics: [
        "Overall accuracy: 95.74%",
        "Macro F1 score: 96.00%",
        "Weighted F1 score: 95.75%",
        "Functional tests passed: 103 out of 107",
        "Non-functional tests passed: 67 out of 67",
        "Hands-on waste segregation result: 83.33% of students segregated correctly",
      ],
    },
    {
      name: "Mirror Your World",
      type: "Academic/personal full-stack project",
      summary:
        "A PHP and MySQL website and appointment-management system for an aluminum and glass installation business.",
      role: "Full-Stack Developer",
      technologies: ["PHP", "MySQL", "JavaScript", "HTML", "CSS", "PHPMailer", "FPDF/TCPDF"],
      features: [
        "Public business website",
        "Customer accounts and appointment scheduling",
        "PDF receipts and email confirmations",
        "Reviews, admin dashboard, blocked calendar dates, invoice creation, and client management",
      ],
    },
    {
      name: "FarmWise",
      type: "Academic/personal web project",
      summary: "A web-based agricultural monitoring and visualization project.",
      role: "Web Developer",
      technologies: ["React", "Material UI", "Recharts"],
      features: ["Agricultural monitoring interface", "Data visualization"],
    },
    {
      name: "JobBridge",
      type: "Academic/personal web project",
      summary:
        "A Laravel-based web application developed as part of my full-stack development experience.",
      role: "Full-Stack Developer",
      technologies: ["Laravel"],
      features: [],
    },
    {
      name: "Microblog",
      type: "Academic/personal mobile project",
      summary: "A mobile application created using Dart and Flutter.",
      role: "Mobile Developer",
      technologies: ["Dart", "Flutter"],
      features: [],
    },
  ],
  careerGoals: [
    "Junior Software Developer",
    "Associate Software Engineer",
    "Full-Stack Developer",
    "Backend Developer",
    "Web Developer",
    "Application Developer",
    "Junior QA Engineer",
    "Software QA Analyst",
    "Junior Automation Tester",
    "AI-assisted development or prompt-engineering roles",
    "Entry-level data or AI-related roles when the requirements match my background",
  ],
  unavailableMessage:
    "I have not included that information in my portfolio, but you can ask me about my experience, projects, technical skills, education, resume, or contact details.",
  localFallbackMessage:
    "I can still help with questions about my experience, technical skills, projects, education, resume, and contact details. Try asking me about one of those areas.",
} as const;

export type PortfolioProfile = typeof portfolioProfile;
export type PortfolioProjectProfile = (typeof portfolioProfile.projects)[number];
